# Generated by Django 4.2.7 on 2023-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('Argentina', 'Argentina'), ('Chile', 'Chile'), ('España', 'España'), ('México', 'México'), ('Perú', 'Perú')], max_length=50)),
                ('delegacion', models.CharField(choices=[('sur', 'Delegación Sur'), ('norte', 'Delegación Norte'), ('este', 'Delegación Este'), ('oeste', 'Delegación Oeste')], max_length=50)),
                ('cliente', models.CharField()),
                ('sector', models.CharField(choices=[('boveda', 'Boveda'), ('caja', 'Caja'), ('atm', 'ATM'), ('otr', 'Otro')], max_length=50)),
                ('saldo', models.CharField(choices=[('saldo', 'Saldo'), ('moneda', 'Moneda'), ('atm', 'ATM')], max_length=50)),
                ('divisa', models.CharField(choices=[('pesos argentinos', 'Pesos argentinos'), ('dolares', 'Dolares'), ('guaranies', 'Guaranies'), ('euros', 'Euros'), ('reales', 'Reales'), ('chq_pesos', 'Chq Pesos'), ('chq_dolares', 'Chq Dolares')], max_length=50)),
                ('tipo', models.CharField(choices=[('bala', 'Bala'), ('pico', 'Pico'), ('bulto_monedas', 'Bulto Monedas')], max_length=50)),
                ('cantidad', models.IntegerField()),
                ('denominacion', models.CharField(choices=[('$1', '$1'), ('$2', '$2'), ('$5', '$5'), ('$10', '$10'), ('$20', '$20'), ('$50', '$50'), ('$100', '$100'), ('$200', '$200'), ('$500', '$500'), ('$1.000', '$1.000'), ('$2.000', '$2.000'), ('$5.000', '$5.000'), ('$10.000', '$10.000'), ('$20.000', '$20.000'), ('$50.000', '$50.000'), ('$100.000', '$100.000')], max_length=50)),
                ('excedente', models.DecimalField(decimal_places=2, max_digits=15)),
                ('faltante', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
