# Generated by Django 4.2.7 on 2023-11-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='denominacion',
            field=models.CharField(choices=[('1', '$1'), ('2', '$2'), ('5', '$5'), ('10', '$10'), ('20', '$20'), ('50', '$50'), ('100', '$100'), ('200', '$200'), ('500', '$500'), ('1000', '$1.000'), ('2000', '$2.000'), ('5000', '$5.000'), ('10000', '$10.000'), ('20000', '$20.000'), ('50000', '$50.000'), ('100000', '$100.000')], max_length=50),
        ),
    ]
